name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "Publish POM"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      SIGNING_KEY_ID: 40D4E7C6
      OSSRH_USERNAME: mjstrasser

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Publish snapshot
        run: ./gradlew publishSnapshot
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        if: github.repository == 'klogging/klogging-spring-boot-starter' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Publish release
        run: ./gradlew publishRelease
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        if: github.repository == 'klogging/klogging-spring-boot-starter' && startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
